### ISSUE TITLE
Canary releases and fire and forget

### ISSUE THREAD

**Issue by ben-foster-cko** [ProxyKit/ProxyKit#151]
Hi Damian,

A while back on Twitter I discussed the possibility of using ProxyKit to test a canary release. The ideal is that we can fire off the canary request and not wait for the response but this is problematic, namely:

- It's possible that the initial http context is disposed before the canary request is complete
- I need to rewind the original request body prior to the canary request being dispatched

To solve this I've had to revert to dispatching the requests sequentially which adds to the overall response time, for example:

```c#
            HttpResponseMessage upstreamResponse = await ForwardAsync(CreateForwardContext(httpContext, routes.PrimaryRoute), routes.PrimaryRoute);

            if (_options.SecondaryGatewayEnabled && routes.HasSecondaryRoute && routes.SecondaryRoute.SupportsReplay)
            {
                await ReplayAsync(httpContext, routes.SecondaryRoute);
            }
```

Would it be possible to clone a `ForwardContext` to support this purpose or are there parts of the API that can be opened up so that we can dispatch the request ourselves using `HttpClient`?

**Comment by damianh** [comment]
Never got around to looking at this ; life has a habbit of getting in the way. Sorry a bout that.

I'm probably not going to explore any further because of #230 however I'll add some additional thoughts I had.

- To issue the same request to two servers, the request will need to be fully buffered. This might create issues for streaming or large payloads.
- You will have to await the result of both to complete the tasks, even if parallel. This could mean your request will be at least as long as the slowest response.
- There are probably going to be some issue with POST/PUT operations that modify any shared backend state
- My understanding is that current practice today is to divert a % percentage of traffic to the canary server (endpoint/instance/service etc) and fall back to a normal if there are any issues (availability / response time /etc). So I don't think I'd go down the route of issue requests twice today.
