### ISSUE TITLE
Is it possible to transfer querystring for websocket proxy

### ISSUE THREAD

**Issue by SFoster84** [ProxyKit/ProxyKit#211]
Hello,

I have some information I pass to my signalr hub during the connection through the querystring.  Is it possible to include that in the proxy?

My current configuration looks like:

    var redirectTo = "https://proxied-server:5002";
    var wssredirectTo = "ws://proxied-server:5002";

    app.UseWebSockets();

    app.UseWebSocketProxy(context => new Uri(wssredirectTo + context.Request.Path.ToString() + context.Request.QueryString.ToString()),
        options => options.AddXForwardedHeaders());

    app.RunProxy(context =>
    {
        var finalUrl = redirectTo + context.Request.Path.ToString();
        var finalContext = context.ForwardTo(finalUrl);
        finalContext.UpstreamRequest.RequestUri = new Uri(finalUrl);

        return finalContext
            .CopyXForwardedHeaders()
            .AddXForwardedHeaders()
            .Send();
    });

**Comment by hoaol** [comment]
I have a similar (or exactly) the same question. I want to add an "access token" to the query string, I have been able to do this but in a not so good way... this works:
```
signalR.UseWebSocketProxy(
   context =>
   {
       var token = Task.Run(async () => await context.GetTokenAsync("access_token")).Result;
       context.Request.QueryString = new QueryString(context.Request.QueryString + "&access_token=" + token);
       return proxyOptions.WsRootUri;
     }
);
```
The bad thing is that I do a Task.Run (since  I can not declare the method as async). I would like to do this in WebSocketClientOptions action like this
```
signalR.UseWebSocketProxy(
   context => proxyOptions.WsRootUri,
                      async (clientOptions) =>
                      {
                            var token = await clientOptions.HttpContext.GetTokenAsync("access_token");
                            clientOptions.HttpContext.Request.QueryString = new QueryString(clientOptions.HttpContext.Request.QueryString + "&access_token=" + token);
                       }
```
 but it seems that I can not change the query string using the HttpContext exposed in the WebSocketClientOptions.
Any suggestion how I can do the manipulation of the query string from the "ClientOptions" metod?

**Comment by damianh** [comment]
Hi,

Sorry for slow response.

That would be nice feature but due to #230 I won't be investing my time in improvements in this area. I'm going point you towards https://github.com/microsoft/reverse-proxy that will hopefully address your issue.

Cheers,

Damian
