### ISSUE TITLE
301 response from upstream service causes InvalidOperationException

### ISSUE THREAD

**Issue by Sebosek** [ProxyKit/ProxyKit#222]
## Version(s)

Version 2.3.2.

## Steps to reproduce

Here is a snippet that can be used for reproducing the problem.

```csharp
public class Startup
{
    public void ConfigureServices(IServiceCollection services) => services.AddProxy();

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        
        app.RunProxy(context => context.ForwardTo("https://httpstat.us/301").Send());
    }
}
```

## Expected behavior

The caller gets an answer after redirect(s).

## Actual behavior

An error is shown to the caller.

## Workarounds

Use the URL on which the caller is redirected.

## Additional context
None

**Comment by damianh** [comment]
I attempted to reproduce the issue here https://github.com/damianh/ProxyKit/commit/9602f2ff908de72dea216d16abe319cc1d0a8eaa however the test passes successfully. Closing as unreproducable. However if you feel their is still an issue, please supply a runnable piece of code (as a PR or self-contained repository) that demonstrates the issue.

Cheers.
